.ORIG x3300

  ST R7, SAVER7 ;Save R7	
  ST R1, SAVER1 ;Save R1	
CHK1 LDI R1, KBSR	
  BRzp CHK1 ;Check KBSR	
  LDI R0, KBDR ;Get the number	
CHK2 LDI R1, DSR	
  BRzp CHK2 ;Check DSR	
  STI R0, DDR ;Post number to DDR	
  LD R1, OFFSET	
  ADD R0, R0, R1	
  LD R1, SAVER1 ;Loads R1	
  LD R7, SAVER7 ;Loads R7	
  RET	

OFFSET .FILL x-30	
SAVER1 .FILL #0	
SAVER7 .FILL #0	
KBSR .FILL xFE00	
KBDR .FILL xFE02	
DSR .FILL xFE04	
DDR .FILL xFE06	
  .END

;Felix Situ and David Bass